import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  contextSidebar: [{ type: "autogenerated", dirName: "0-context" }],
  researchSidebar: [{ type: "autogenerated", dirName: "1-research" }],
  synthesisSidebar: [{ type: "autogenerated", dirName: "2-synthesis" }],
};

export default sidebars;
